### ISSUE TITLE
Should the repository be called omdbtool or omdb-cli?

### ISSUE THREAD

**Issue by kenorb** [bgr/omdb-cli#9]
As per recent change from `imdbtool.py` to `omdbtool.py`, I believe the repository name should be renamed as well to keep it consistent.

**Comment by bgr** [comment]
I decided to leave it as-is to avoid breaking other people's links and who knows what else (unless github will do the redirect?). I'll leave this issue open and if more people vote for name change I'll gladly change it, thanks for bringing it up!

**Comment by kenorb** [comment]
On GitHub, if you rename the repo name, it's redirecting old links to the new one (even for the git remotes).

**Comment by bgr** [comment]
Renamed!
